default: &default
  adapter: cockroachdb
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portal_development

test:
  <<: *default
  database: portal_test

production:
  <<: *default
  database: portal_production
  username: portal
  password: <%= ENV["PORTAL_DATABASE_PASSWORD"] %>
